---
title: "SEFL20_Analysis"
author: "Zach"
output:
  html_document:
    fig_height: 4.5
    fig_width: 4.5
    highlight: kate
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 6
  pdf_document:
    toc: yes
    toc_depth: '6'
editor_options: 
  chunk_output_type: console
---


# Set Global Options
```{r global_options}
knitr::opts_chunk$set(fig.width=4.5, fig.height=4.5, echo=TRUE, warning=FALSE,message=FALSE)
```



# Load Packages 
```{r}
library(ggplot2)
library(ez)
library(knitr)
library(tidyr)
library(dplyr)
library(purrr)
```


# Import Data 
Load  files and factorize as necessary.
```{r}

#load  files
data_vf = read.csv('SEFL20_vfdata.csv',header=TRUE)
groups = read.csv('SEFL20_groups.csv',header=TRUE)

#factorize as necessary
groups$Animal = factor(groups$Animal)
data_vf$Animal = factor(data_vf$Animal)
 
# #add group info to data files
data_vf = right_join(x=groups,y=data_vf,by="Animal")

```


# Subset data
Separate phases (trauma, trauma recall, etc) are placed in unique dataframes for ease of analysis.
```{r}

#Context A tone-shock acquisition
A_acq.fz = data_vf[
  data_vf$phase=='A_training' & (data_vf$subphase!='bl' | data_vf$subphase!='cs'),
  ]

#trauma data
trauma.freezing = data_vf[data_vf$phase=='trauma' & data_vf$subphase!="shock",]

#trauma test data
traumatest = data_vf[data_vf$phase=='traumatest' & data_vf$subphase=='avg',]

#Final tone tests
#Only first tone test included here.  Second tone test to novel tone, and
#third tone test back with trained tone
tone_tests = data_vf[
  data_vf$phase=='C_tonetest' & 
    data_vf$subphase=='1' & 
    data_vf$subsubphase!='shock' & 
    data_vf$subsubphase!='post',]

```


# Get stats for plotting
Calculate relevant means and std. errors.
```{r}


A_acq.fz.stats = summarize_at(
  .tbl = group_by(A_acq.fz, subphase, component, Trauma),
  .funs = list(mean=~mean(.), sem=~sd(.)/sqrt(n())),
  .vars = c('freezing','motion'))

trauma.freezing.stats = summarize_at(
  .tbl = group_by(trauma.freezing, component, Trauma),
  .funs = list(mean=~mean(.), sem=~sd(.)/sqrt(n())),
  .vars = c('freezing','motion'))

traumatest.stats = summarize_at(
  .tbl = group_by(traumatest, component, Trauma),
  .funs = list(mean=~mean(.), sem=~sd(.)/sqrt(n())),
  .vars = c('freezing','motion'))

tt.stats = summarise_at(
  .tbl = group_by(tone_tests,subsubphase,component,Trauma),
  .funs = list(mean=~mean(.), sem=~sd(.)/sqrt(n())),
  .vars = c('freezing','motion'))

```



# Plots
## Global Plot Parameters
```{r}

#set figure file prefix
f_pfx = '20'

#ggsave
p.save = TRUE

#Plot dimensions
p.dim.width = 4.5 #Plot width (in)
p.dim.height = 4.5 #Plot height (in)
p.dim.dpi = 500 #Plot dpi

#Plot text
p.textsize.title = 20
p.textsize.legend =10
p.textsize.axis.title = 13
p.textsize.axis.text = 12

#Plot colors
p.scale.colour = c("white","thistle4","#26466D","red4",'paleturquoise4')
p.scale.fill = c("white","thistle4","#26466D","red4",'paleturquoise4')
#p.scale.fill = c("white","darkgray","royalblue4","red2",'darkgreen')

#Plot line dimensions
p.line.data.size = 1
p.line.axis.size = .5
p.line.bar.size = .7
p.line.error.size = .75

#Widths
p.width.bar = .8
p.width.jitter = .3
p.width.error = .5

#Point/dot sizes
p.point.shape = 21
p.point.size = 4
p.point.stroke = 1
p.dot.size = 2.5
p.dot.shape = 21
p.dot.alpha = .3

p.legend.position = c(.22,.9)
p.margin1 = unit(c(2,3.25,2.45,3.25), "cm") #(top,right,bottom,left)

#base theme
p.basetheme = theme_bw() + theme(
    panel.grid = element_blank(), 
    panel.border = element_rect(colour = "white"),
    axis.line = element_line(color="black", size = p.line.axis.size),
    plot.title = element_text(
      size=p.textsize.title, 
      hjust=.5, margin=margin(b=15,t=10), 
      face="bold"),
    axis.title = element_text(size=p.textsize.axis.title, face="bold"),
    axis.title.x = element_text(margin=margin(t=-3)),
    axis.text= element_text(size=p.textsize.axis.text,colour="black"),
    axis.text.x= element_text(
      size=p.textsize.axis.title,
      face='plain',
      angle = 0,
      vjust=.5,
      margin=margin(b=10,t=5)),
    legend.position = p.legend.position,
    legend.title = element_blank(),
    legend.text = element_text(size=p.textsize.legend, face="bold"),
    legend.key = element_rect(colour=NA,fill=NA),
    legend.background = element_rect(fill=NA),
    plot.background = element_rect(fill = "transparent",colour = NA),
    plot.margin = p.margin1
  ) 


#predefine partial function for saving plots
saveplot = partial(
  ggsave,
  width = p.dim.width,
  height = p.dim.height,
  units = "in",
  dpi = p.dim.dpi,
  bg = 'transparent'
)

```


## Make Plots
### Tone-Shock Acquisition in A
```{r, fig.width=4.5, fig.height=4.5}

#Create base layer from group level data
P.A_acq.fz = ggplot(
  data = A_acq.fz.stats[A_acq.fz.stats$subphase=='bl' | A_acq.fz.stats$subphase=='cs', ],
  aes(x=component,
      y=freezing_mean,
      fill=Trauma,
      shape=Trauma,
      group=interaction(Trauma,subphase)))

#Define plot specific parameters
p.ymin = 0
p.ymax = 80
p.yint = 20
p.breaks = seq(p.ymin,p.ymax,p.yint)

#Create plot
P.A_acq.fz  +
  
  geom_errorbar(
    stat="identity",
    size=p.line.error.size,
    colour = "black",
    aes(ymin = freezing_mean - freezing_sem,
        ymax = freezing_mean + freezing_sem,
        width = p.width.error)) +
  
  geom_line(
    stat="identity",
    size = p.line.data.size
  ) +
  
  geom_point(
    stat = "identity",
    size = p.point.size,
    shape = p.point.shape,
    stroke = p.point.stroke
  ) +
  
  scale_fill_manual(values=p.scale.colour) +
  
  coord_cartesian(ylim=c(p.ymin,p.ymax)) +
  scale_y_continuous(breaks=p.breaks, expand = c(0, 0)) +
  scale_x_discrete(labels=c('bl','1','2','3')) +
  
  labs(
    x = "Tone",
    y = "% Freezing"
  ) +
  
  p.basetheme 

if (p.save == TRUE) {saveplot(filename = paste(f_pfx, "AcqA.tiff", sep = '_'))}

```



### Post-Trauma Tests in C
```{r, fig.width=4.5, fig.height=4.5}

#Create base layer from group level data
P.ToneTest.Freezing = ggplot(
  data = tt.stats,
  aes(x=component,
      y=freezing_mean,
      fill=Trauma,
      shape=Trauma,
      group=interaction(Trauma,subsubphase))) 

#Define plot specific parameters
p.ymin = 0
p.ymax = 80
p.yint = 20
p.breaks = seq(p.ymin,p.ymax,p.yint)

#Create plot
P.ToneTest.Freezing  +
  
  geom_errorbar(
    stat="identity",
    size=p.line.error.size,
    colour = "black",
    aes(ymin = freezing_mean - freezing_sem,
        ymax = freezing_mean + freezing_sem,
        width = p.width.error)) +
  
  geom_line(
    stat="identity",
    size = p.line.data.size
  ) +
  
  geom_point(
    stat = "identity",
    size = p.point.size,
    shape = p.point.shape,
    stroke = p.point.stroke
  ) +
  
  scale_fill_manual(values=p.scale.colour) +
  
  coord_cartesian(ylim=c(p.ymin,p.ymax)) +
  scale_y_continuous(breaks=p.breaks, expand = c(0, 0)) +
  scale_x_discrete(labels=c('bl','1','2','3')) +
  
  labs(
    x = "Tone",
    y = "% Freezing"
  ) +
  
  p.basetheme +

if (p.save == TRUE) {saveplot(filename = paste(f_pfx, "TestC.tiff", sep = '_'))}

```


# Stats
```{r}


tone_acq.bl = ezANOVA(
  data = A_acq.fz[A_acq.fz$subphase=='bl',],
  dv = freezing,
  wid = Animal,
  between = .(Trauma),
  type = 3,
  detailed = TRUE
)
tone_acq.bl

tone_acq.cs = ezANOVA(
  data = A_acq.fz[A_acq.fz$subphase=='cs',],
  dv = freezing,
  wid = Animal,
  within = .(component),
  between = .(Trauma),
  type = 3,
  detailed = TRUE
)
tone_acq.cs


tone_test.bl = ezANOVA(
  data = tone_tests[tone_tests$subsubphase=='bl',],
  dv = freezing,
  wid = Animal,
  between = .(Trauma),
  type = 3,
  detailed = TRUE
)
tone_test.bl

tone_test.cs = ezANOVA(
  data = tone_tests[tone_tests$subsubphase=='cs',],
  dv = freezing,
  wid = Animal,
  within = .(component),
  between = .(Trauma),
  type = 3,
  detailed = TRUE
)
tone_test.cs


```



